import = [ 
    #"~/.config/alacritty/themes/themes/marine_dark.toml" 
    "~/.config/alacritty/themes/themes/seashells.toml"
]

[keyboard]
bindings = [
    { key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]

[font]
offset.x = 0
offset.y = 2

[font.normal]
family = "Cozette"
style = "Medium"

[font.bold]
family = "Cozette"
style = "Medium"

[font.bold_italic]
family = "Cozette"
style = "Medium"

[font.italic]
family = "Cozette"
style = "Medium"

[window]
opacity = 0.7

[window.padding]
x = 15
y = 15

[cursor.style]
blinking = "Always"

[env]
WINIT_X11_SCALE_FACTOR = "1"

[colors.normal]
blue = "#739DA8"

