# Default colors
[colors.primary]
foreground = '#c2bda6'
background = '#48463d'

[colors.cursor]
cursor = '#c2bda6'
text = '#48463d'

[colors.selection]
background = '#c2bda6'
text = '#48463d'

# Normal colors
[colors.normal]
black   = '#48463d'
red	= '#c2bda6'
green   = '#c2bda6'
yellow  = '#9d0006'
blue	= '#c2bda6'
magenta = '#c2bda6'
cyan    = '#c2bda6'
white   = '#c2bda6'

# Bright colors
#[colors.bright]
#black   = '#23272c'
#red     = '#66a5cc'
#green   = '#59b0f2'
#yellow  = '#4bb0d3'
#blue    = '#487092'
#magenta = '#50829e'
#cyan    = '#658795'
#white   = '#4d676b'
