# Default colors
[colors.primary]
background = '#c2bda6'
foreground = '#48463d'

[colors.cursor]
text = '#c2bda6'
cursor = '#48463d'

[colors.selection]
text = '#c2bda6'
background = '#48463d'

# Normal colors
[colors.normal]
black   = '#c2bda6' # Main Beige
# red     = '#076678' # Navy
red	= '#48463d' # Dark Red
green   = '#48463d' # Orange
yellow  = '#9d0006' # Eggshell | htop bold
# blue    = '#9d0006' # Dark Red
blue	= '#48463d' # Navy | Folders, Comments
magenta = '#48463d' # Dark Green | htop user is process
cyan    = '#48463d' # Main Grey
white   = '#48463d' # Main Grey | CLI Suggestions, Path

# Bright colors
#[colors.bright]
#black   = '#23272c'
#red     = '#66a5cc'
#green   = '#59b0f2'
#yellow  = '#4bb0d3'
#blue    = '#487092'
#magenta = '#50829e'
#cyan    = '#658795'
#white   = '#4d676b'
