version = "1.1.13"

[format]
# Deduplicate icons if enable.
# A superscripted counter will be added.
dedup = false
# dedup_inactive_fullscreen = false # dedup more
# window delimiter
delim = "<span size='14pt'> </span>"
# max_clients = 30 # you should not need this

# available formatter:
# {counter_sup} - superscripted count of clients on the workspace, and simple {counter}, {delim}
# {icon}, {client}
# workspace formatter
workspace = "<span rise='3pt'>[{id}]</span> <span font_family='CozetteHiDpi' size='16pt'>{clients}</span>" # {id}, {delim} and {clients} are supported

workspace_empty = "<span rise='3pt'>[{id}] EMPTY</span>"
client = "<span color='gray'>{icon}</span>"
client_active = "<span color='#E5C49E'>{icon}</span>"

# deduplicate client formatter
client_fullscreen = "{icon}"
client_dup = "{client}{counter_sup}"
#client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused}"

[class]
# Add your icons mapping
#"DEFAULT" = " {class}: {title}"
"DEFAULT" = "{class}"
"(?i)brave-browser*" = ""
"(?i)alacritty*" = ""
"MuPDF" = ""
"Code" = "<span></span>"
"thunar" = ""
"libreoffice-writer" = ""
"libreoffice-impress" = "<span></span>"
"libreoffice-calc" = ""
"org.pwmt.zathura" = ""
"eog" = ""
"[Ff]irefox" = "browser"
"(?i)waydroid.*" = "droid"

[class_active]
"DEFAULT" = "{class}"
"thunar" = "<span color='#E5C49E'></span>"

# [initial_class]
# "DEFAULT" = " {class}: {title}"
# "(?i)Kitty" = "term"

# [initial_class_active]
# "(?i)Kitty" = "*TERM*"

[title_in_class."(?i)kitty"]
"(?i)neomutt" = "neomutt"
# regex captures support is supported
# "emerge: (.+?/.+?)-.*" = "{match1}"

[title_in_class."(?i)alacritty"]
"(?i)yazi" = ""
"nvim" = ""
"btop" = ""

[title_in_class_active."(?i)alacritty"]
"(?i)yazi" = "<span color='#E5C49E'></span>"

[title_in_class_active."(?i)firefox"]
"(?i)twitch" = "<span color='purple'>{icon}</span>"

# [title_in_initial_class."(?i)kitty"]
# "(?i)neomutt" = "neomutt"

# [initial_title_in_class."(?i)kitty"]
# "(?i)neomutt" = "neomutt"

# [initial_title_in_initial_class."(?i)kitty"]
# "(?i)neomutt" = "neomutt"

# [initial_title."(?i)kitty"]
# "zsh" = "Zsh"

# [initial_title_active."(?i)kitty"]
# "zsh" = "*Zsh*"

# Add your applications that need to be exclude
# The key is the class, the value is the title.
# You can put an empty title to exclude based on
# class name only, "" make the job.
[exclude]
"" = "^$" # prevent displaying icon for empty class
"(?i)fcitx" = ".*" # will match all title for fcitx
"(?i)TestApp" = "" # will match all title for TestApp
aProgram = "^$" # will match null title for aProgram
"[Ss]team" = "^(Friends List.*)?$" # will match Steam friends list plus all popups (empty titles)

[workspaces_name]
0 = "zero"
1 = "one"
2 = "two"
3 = "three"
4 = "four"
5 = "five"
6 = "six"
7 = "seven"
8 = "eight"
9 = "nine"
10 = "ten"
